
[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[window]
# padding = { x = 3, y = 3 }
dynamic_padding = true
decorations = "None"

[general]
import = [
  "/home/im3shn/dotfiles/alacritty/.config/alacritty/themes/themes/rose-pine.toml"
]
# opacity = 0.70

